#!/usr/bin/env ruby

# This script is for doing things like...
# - Building docker containers for development and production
# - Building base docker images on top of which the app container is built
# - Running tests in docker enabling us to run tests in a production like environment

require 'optparse'
require 'json'
require 'pp'
require 'fileutils'
require 'pathname'
require 'highline/import'
require 'colorize'

include FileUtils

# Log levels
$log_levels = {
  :info => {
    'string' => 'info',
    'color' => :green
  },
  :warn => {
    'string' => 'warn',
    'color' => :magenta
  },
  :debug => {
    'string' => 'debug',
    'color' => :yellow
  },
  :error => {
    'string' => 'error',
    'color' => :red
  }
}

ARGV << '-h' if ARGV.empty?

def get_options
  defaults = {}
  options = {}

  OptionParser.new do |opts|
    opts.banner = "Usage: sdk [options]"

    # Configure default options
    defaults[:environment] = 'development'

    # Cluster Control
    opts.separator ''
    opts.separator 'Cluster Control'

    opts.on('-c [action]', '--cluster', 'Run an action on the local cluster - Actions: up, down') { |v| options[:cluster] = v || 'up' }
    opts.on('-l [service]', '--logs', 'Show logs from the cluster (defaults to all services)') { |v| options[:logs] = v || 'all' }
    opts.on('-r [service]', '--restart', 'Restart services (defaults to all services)') { |v| options[:restart] = v || 'all' }

    # Setup
    opts.separator ''
    opts.separator 'Setup'
    # The setup feature is a work in progress...
    #opts.on('-s', '--setup', 'Set up local environment for building and working with docker images') { options[:setup] = true }
    opts.on('-I', '--vpnimport', 'Import VPN configuration') { options[:vpnimport] = true }
    opts.on('-i', '--init', 'Create a user, activate that user, then log in and provide bridge info') { options[:init] = true }

    # Service & Vendor Package Version Control
    # Here we'll control updating versions (branch, hash, tag) of the storj service submodules
    # as well as dependency submodules
    opts.separator ''
    opts.separator 'Version Management'
    opts.separator 'In the following context, version can refer to a branch, hash, or tag'
    opts.on('-v [service]@[version]', '--sversion', Array, 'Set the version of a storj service') { |v| options[:version] = v || 'list' }
    opts.on('-u [module]', '--update', 'Update local module from remote (defaults to all)') { |v| options[:update] = v || 'all' }

    # Building
    opts.separator ''
    opts.separator 'Building & Publishing'

    opts.on('-b [image]', '--build', 'Build a docker image',
            '   Image Types: os, deps, *all, [service]') { |v| options[:build] = v || 'all' }

    opts.on('-p', '--push', 'Push a docker image for an application to the docker hub') { |v| options[:push] = true }
    opts.on('-C', '--clean', 'Clean local state') { |v| options[:clean] = v || 'all' }

    opts.separator ''
    opts.separator 'Common options'
    opts.separator "To build, run, or push  you must choose either an environment to build the application for"
    opts.on('-e', '--environment', 'Environment for which we are building our application') { |v| options[:build] = v }
    opts.on('-d', '--debug', 'Enable debug logging') { |v| options[:debug] = v }

    # Tests & Benchmarking
    opts.separator ''
    opts.separator 'Testing ( coming soon... )'

    opts.on('-t [type]', '--test', 'Run tests - Test Types: *integration, unit') { |v| options[:test] = true }

    opts.separator ''
    opts.separator 'Global Options'
    opts.on('-x', '--no-cache', 'Run build actions with no-cache option to pull latest dependencies') { |v| options[:nocache] == true }
    opts.on('-y', '--yes', 'Do not prompt to confirm any actions') { |v| options[:yes] = true }

    opts.on_tail('-h', '--help', 'Show this message') do
      puts opts
      exit
    end
  end.parse!

  return options
end

def yesno(prompt = 'Continue?', default = true)
  a = ''
  s = default ? '[Y/n]' : '[y/N]'
  d = default ? 'y' : 'n'
  until %w[y n].include? a
    a = ask("#{prompt} #{s} ") { |q| q.limit = 1; q.case = :downcase }
    a = d if a.length == 0
  end
  a == 'y'
end

# Run a system command with real time output
def run_command(intent, command = '')
  confirm = true

  # If an intent is not specified, do not confirm
  if command == '' && intent
    command = intent
    confirm = false
  end

  if confirm
    response = yesno("Are you sure you want to #{intent}?");

    if !response then abort "Aborting..." end
  end

  result = {}

  result['output'] = `#{command}`
  result['success'] = $?.success?
  result['status'] = $?.exitstatus

  return result
end

def get_nodejs_project_version()
  package_file = File.read('package.json')
  package_data = JSON.parse(package_file)
  package_version = package_data['version']
  return package_version
end

def check_deps()
  # Check for..
  # jq
  # expect
end

def start
  options = get_options

  $yes_to_all = options[:yes]
  $debug = options[:debug]

  # Check dependencies here
  check_deps()

  if options[:setup]
    # Determine the OS we're working with

    # Check to see if docker is already installed

    # If not, install docker

    # Download the latest docker for mac image
    docker_dmg_url = "https://download.docker.com/mac/stable/Docker.dmg"
    docker_dmg_file = "Docker.dmg"
    download_path = "/tmp/#{docker_dmg_file}"

    result = `wget -O #{download_path} #{docker_dmg_url}`

    # Mount the dmg
    mount_point = Pathname.new "/Volumes/#{docker_dmg_file}"
    result = `hdiutil attach -mountpoint #{mount_point} #{download_path}`

    # Find the app in the mounted dmg
    files = mount_point.entries.collect { |file| mount_point+file }
    files.reject! { |file| ((file.to_s.include?(".app")) ? false : true) }

    # Copy the app to Applications folder
    files.each { |app|
      # Make sure the app doesn't already exist. If it does, prompt to overwrite/upgrade
      if FileTest.exist?("/Applications/#{app}")
        puts "It appears you already have #{app} installed. What shall we do?"
        puts yesno("Overwrite existing application?");
      end

      puts "Copying #{app} to Applications folder"
      `cp -a #{app} /tmp/Applications/`
    }

    # Unmount the dmg
    puts "Unmounting #{docker_dmg_file}"
    result = `hdiutil detach #{mount_point}`
    puts "Finished installing #{docker_dmg_file}"

    # Clean up after ourselves
    rm docker_dmg_file
  end

  if options[:vpnimport]
    run_command('open vpn/storj-local.ovpn')
  end

  if options[:init]
    log_it("Initializing all service submodules...")
    output = `git submodule update --init --recursive`
    log_it("#{output}", :debug)

    log_it("Checking dependencies...")
    output = `./scripts/check_dependencies.sh`
    log_it("#{output}")

    log_it("Bringing up your cluster...")
    output = `docker-compose up -d`

    rsp_code = ""

    log_it("Checking for connectivity to local bridge server... Please wait.")
    # Get the local bridge and attempt to ping it
    while rsp_code != "200"
      rsp_code = `curl -m 5 -s -o /dev/null -w "%{http_code}" $(./scripts/get_local_bridge.sh)`
      # If we cannot ping it, we're likely not connected to the VPN so prompt the user to do so here
      if rsp_code != "200"
        log_it("We are unable to connect to the local bridge service. Please ensure that your VPN connection has been configured", :warn)
        log_it("Please refer to the readme for help with importing the VPN configuration for the first time")
        continue = yesno("Once you have connected to VPN please continue")
        if !continue
          exit 0
        end

        log_it("Trying again...")
      end
    end

    log_it("Connected to local bridge successfully!")

    log_it("Adding a test user to the bridge...")
    output = `./scripts/add_user.sh`
    log_it("#{output}", :debug)

    log_it("Logging in test user...")
    output = `./scripts/login_user.sh`
    log_it("#{output}", :debug)

    log_it("Setting host entries for bridge and bridge-gui. You may be asked for sudo password...")
    output = `./scripts/set_host_entries.sh`
    log_it("#{output}", :debug)

    log_it("Done.")

    log_it("If you're on OSX, be sure to import the ./vpn/storj-local.ovpn config and connect to the VPN")
    log_it("Please run 'source scripts/setbr' to set your local bridge")
  end

  if options[:cluster]
    if options[:cluster] == 'up'
      log_it("Bringing up cluster...")
      run_command('docker-compose up -d')
      #log_it("If you're on OSX, be sure to import the ./vpn/storj-local.ovpn config and connect to the VPN")
      #log_it("Please run '. scripts/setbr' to set your local bridge")
    end

    if options[:cluster] == 'down'
      run_command('docker-compose down')
    end
  end

  if options[:clean]
    if options[:clean] == 'all'
      clean_share
      clean_mongo
    end

    if options[:clean] == 'docker'
      clean_docker
    end

    if options[:clean] == 'share'
      clean_share
    end

    if options[:clean] == 'mongo'
      clean_mongo
    end

    if options[:clean] == 'vpn'
      clean_vpn
    end
  end

  if options[:version]
    log_it('Updating service versions...')

    log_it("Version string is: #{options[:version]}", :debug)

    if options[:version] == 'list'
      log_it('Current module versions')
      result = run_command("git submodule status")
      puts("#{result['output']}")
    else
      services = parse_services(options[:version])
      log_it("Services is: #{services}", :debug)

      if services
        services.each do |service|
          if service['name'] && service['version']
            # We should check to see if this is a core service or a dependency
            # If it is a vendored dependency, check to see if we have a submodule for it already
            # If not, check out the submodule into the vendor folder and continue

            run_command("git --git-dir=./.git/modules/#{service['name']} fetch")
            run_command("git --git-dir=./.git/modules/#{service['name']} checkout #{service['version']}")
            log_it("Updated version of #{service['name']} to #{service['version']} locally. Don't forget to commit and push if desired")
          else
            log_it('Please provide a service name and version', :error)
          end
        end
      end
    end
  end

  if options[:update]
    # Should add the ability to do sdk -u bridge@v4.0.0 or somehow define local module
    # Currently default is all
    run_command('git submodule update --recursive')
  end

  if options[:build]
    build_opts = ''
    if options[:nocache]
      build_opts += ' --no-cache'
    end
    #environment = options[:environment]  || 'prod'
    if options[:build] == 'services'
      if options[:nocache]
        run_command('rebuild all with no cache', 'docker-compose build --no-cache')
      end

      run_command('build all services', 'docker-compose up --build -d')

    elsif options[:build] == 'baseall'
      run_command('build a new os base image', "docker build #{build_opts} -t storjlabs/deps-os:1 -t storjlabs/deps-os:latest -f ./dockerfiles/os.base.dockerfile .")
      run_command('build a new dependencies base image', "docker build #{build_opts} -t storjlabs/deps-base:1 -t storjlabs/deps-base:latest -f ./dockerfiles/deps.base.dockerfile .")
    elsif options[:build] == 'os'
      run_command('build a new os base image', "docker build #{build_otps} -t storjlabs/deps-os:1 -t storjlabs/deps-os:latest -f ./dockerfiles/os.base.dockerfile .")
    elsif options[:build] == 'deps'
      run_command('build a new dependencies base image', "docker build #{build_opts} -t storjlabs/deps-base:1 -t storjlabs/deps-base:latest -f ./dockerfiles/deps.base.dockerfile .")
    elsif options[:build] == 'all'
      if options[:nocache]
        run_command("build service #{options[:build]} with no-cache", "docker-compose build --no-cache")
      end

      run_command("build service #{options[:build]}", "docker-compose up --build -d")
    else
      log_it("Unknown service #{options[:build]}")
    end
  end

  if options[:restart]
    if options[:restart] == 'all'
      run_command('Restarting all services', 'docker-compose restart')
    else
      run_command("Restarting service #{options[:restart]}", "docker-compose restart #{options[:restart]}")
    end
  end

  if options[:logs]
    if options[:logs] == 'all'
      run_command('docker-compose logs -f')
    else
      run_command("docker-compose logs -f #{options[:logs]}")
    end
  end

  if options[:push]
    version = options[:versin] || 'latest'
    app_name = options[:app]
    image_name = "storjlabs/#{app_name}:#{version}"
    puts "Pushing image '#{image_name}' to the docker hub"

    run_command("docker push #{image_name}")
  end
end

def clean_docker
  run_command('clean docker', 'docker-compose down --rmi all')
end

def clean_share
  run_command('clean share', 'git clean -fdx share/instances/')
end

def clean_mongo
  run_command('clean mongo', 'git clean -fdx mongodb/data/')
end

def clean_vpn
  run_command('clean vpn', 'git clean -fdx vpn/config/ && rm vpn/storj-local.ovpn')
end

def parse_services(services)
  services_arry = []

  # Then see if a version was included and split by that if necessary
  services.each do |svc|
    split_svc = svc.split("@")
    svc_name = split_svc[0]

    if split_svc.length == 2
      svc_version = split_svc[1]
    end

    svc_obj = {
      "name" => svc_name,
      "version" => svc_version
    }

    services_arry.push(svc_obj)
  end

  # How do we handle no version? How do we determine latest?

  return services_arry
end

def log_it(log_line, level = :info)
  color = $log_levels[level]['color']
  level_string = $log_levels[level]['string']

  # Dont log if the line is debug and we dont have the verbose flag
  if level == :debug && !$debug
    return
  end

  puts "[#{level_string}]".colorize(color) + " #{log_line}"
end

start()
