#!/bin/bash

SERVICE_TO_WATCH=$1
SERVICE_ROOT_DIR=$2
SERVICE_WATCHER_PATH=./$SERVICE_ROOT_DIR/files/scripts/nodemon_watcher.js

nodemon $SERVICE_WATCHER_PATH --watch ./$SERVICE_ROOT_DIR/$SERVICE_TO_WATCH/ ./$SERVICE_ROOT_DIR/$SERVICE_TO_WATCH/Dockerfile
